# Site
name: 'Sabbir Prime'
description: 'Hey There! Welcome To My Blog. This is Sabbir Hasan Munna. I am Just A Hobby Dev. Ad I love Coding And Tech Stuff.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'Sabbirs Blog'
email: 'sabbirhasan2999@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Sabbir
      site:           sabbirprime.me
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Sabbir"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/sabbir2609
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
